language: python

python:
  - "2.7"

sudo: false
cache: pip

addons:
  postgresql: "9.6"
  apt:
    packages:
      - expect-dev  # provides unbuffer utility

env:
  global:
  - VERSION="10.0" TESTS="0" LINT_CHECK="0" MAKEPOT="0"
  - WKHTMLTOPDF_VERSION="0.12.4"

  matrix:
  - LINT_CHECK="1"
  - TESTS="1" ODOO_REPO="odoo/odoo" LINT_CHECK="0" EXCLUDE=delivery_price_rule_untaxed MAKEPOT="1"
  - TESTS="1" ODOO_REPO="OCA/OCB" LINT_CHECK="0" EXCLUDE=delivery_price_rule_untaxed
  - TESTS="1" ODOO_REPO="odoo/odoo" LINT_CHECK="0" EXCLUDE=delivery_price_by_category MAKEPOT="1"
  - TESTS="1" ODOO_REPO="OCA/OCB" LINT_CHECK="0" EXCLUDE=delivery_price_by_category

virtualenv:
  system_site_packages: true

install:
  - git clone --depth=1 https://github.com/OCA/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly
  - pip install PyPDF2==1.18
  - pip install unidecode
  - pip install pycountry
  - pip install suds-jurko==0.6

script:
  - travis_run_tests

after_success:
  - travis_after_tests_success
